### ISSUE TITLE
OffsetSerDeTest fails on Windows due to line separator

### ISSUE THREAD

**Issue by ejpearson** [salesforce/mirus#17]
Currently both cvsList and jsonList end their Strings with \n: 

`
"connector-id,topic,1,123\n",
`

This causes the tests to fail on Windows.

The tests should either not include the line separator or take into account the System.lineSeparator()

**Comment by pdavidson100** [comment]
@ejpearson Let us know if the test works on Windows now.

**Comment by ejpearson** [comment]
Yes, it fixed the test.  All tests now pass.
