### ISSUE TITLE
Getting Mirus JMX Metrics 

### ISSUE THREAD

**Issue by PabloInnocenti** [salesforce/mirus#21]
Dear Mirus Team,

First of all, thanks for this excellent project.

We start a connector cluster (consisting in 3 connector worker servers)  and copy mirus jar library to plugin directory and successfully replicate topics from one cluster (origin) to another (destination).

We would like to use JMX metrics to monitor mirus status in the connector cluster. 

We found in project source class (AbstractMirusJmxReporter): 
`metrics.addReporter(new JmxReporter("mirus"));`

and in ConnectorJmxReporter class: 
`private static final String CONNECTOR_JMX_GROUP_NAME = "connector-metrics";`

We try to get the Mbean path using visualVM, but we couldn't find the mirus path in JVM Mbeans.
Do we need to enable something in configuration?

Regards,
Pablo

**Comment by pdavidson100** [comment]
No special configuration required.  One thing to be aware of is that the "connector-metrics" group will only be available if you start the worker processes using `Mirus.main`.  `ConnectDistributed.main` does not initialize the HerderMonitor class.

Another thing to be aware of is that, by default, KafkaConnect does not separate JMX bean names so you will not see valid metrics for all tasks. We have submitted a bug fix PR for this, but have not had any success getting it reviewed and accepted yet.  See https://issues.apache.org/jira/browse/KAFKA-5061.

**Comment by PabloInnocenti** [comment]
Thank you very much! 

We run using mirus-worker-start.sh and add environments options and get jmx connectors metrics (running-task-count, etc) as we create them.
You can close the issue.

Regards,
Pablo.

**Comment by pdavidson100** [comment]
Thanks Pablo!
