### ISSUE TITLE
Getting similar function as "measuring lag" (mirrormaker) in mirus 

### ISSUE THREAD

**Issue by PabloInnocenti** [salesforce/mirus#29]
Dear Mirus team,

We would like to monitor how far is topic replica from one cluster to another using mirus. Using mirror-maker we use the following to monitor "lag":

`kafka-consumer-groups.sh --bootstrap-server localhost:9092 --group mirroring-data --describe`

`TOPIC PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG CONSUMER-ID HOST CLIENT-ID`

Where LAG is obtained from log-end-offset (highwatermark) minus current-offset.

How can we do a similar function using mirus? We can access to mirus jmx values.

Thanks,
Pablo.

In kafka connect we can access the latest offset in the group_offset connect topic.
`kafka-console-consumer.sh --bootstrap-server localhost:9092 --property print.key=true --topic mirus-offsets`

Theres a KIP in kafka [KIP-196](https://cwiki.apache.org/confluence/display/KAFKA/KIP-196%3A+Add+metrics+to+Kafka+Connect+framework) in WIP for Add metrics to Kafka Connect framework.

**Comment by pdavidson100** [comment]
To calculate lag we actually use an ad-hoc script that calls `bin/mirus-offset-tool.sh` to grab the current offsets and `kafka.tools.GetOffsetShell` to grab the high-watermarks.  

Lag reporting could be added to `mirus-offset-tool.sh`, but that would require grabbing the current connector configuration to find the correct source cluster and topic. It's something we haven't added as have not had an urgent need, and wanted to keep the offset tool as simple as possible. If someone did want to add lag functionality to `mirus-offset-tool` I think it would be useful.

**Comment by PabloInnocenti** [comment]
Hi pdavidson100,

Thanks for the help. We decided to make a python script for now.

We generate a python code to retrieve high-watermarks from shell using command
`bin/kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list <brokers>:9092 --time -2 --topic <topiname>`  for every topic where --broker-list refers to **origin** kafka cluster to replicate.
 
Then we use `bin/mirus-offset-tool.sh` to get a list of offsets by partition (per topic), which we presume that it uses **destination** kafka cluster (defined in worker.properties in property bootstrap.servers). 

When doing HW - Offset for every partition we get negative values. Is is correct the way we have configured mirus? (worker.properties in property bootstrap.servers)

Thanks,
Pablo.

**Comment by pdavidson100** [comment]
`mirus-offset-tool.sh`should use the cluster defined in`bootstrap.servers` in your `worker.properties` file.  Typically that would be the destination cluster, but you are free to configure Mirus to use the source cluster for storing offsets if that makes for sense for you.  

I have never seen a negative offset value returned before, but this probably means Mirus is struggling to read or write the associated partitions. Have you confirmed there are at least a few records in the source partitions? Negative offsets can be associated with truncated partitions, which happens when data ages out.

**Comment by cricket007** [comment]
Other options include tool like LinkedIn's Burrow or [Remora](https://github.com/zalando-incubator/remora)

**Comment by PabloInnocenti** [comment]
Thanks both!
We resolve the issue. The problem was the time elapsed between getting watermark of every topic (this command run individually for every topic and we have many topics) and running mirus offset tool ( which delivers all topics offset). 
We will checkout Remora.

You can close the issue.
Thanks!

**Comment by pdavidson100** [comment]
Thanks @PabloInnocenti
