### ISSUE TITLE
Artifacts on Maven Central

### ISSUE THREAD

**Issue by jamesward** [salesforce/mirus#3]
It'd be great to have this deployed on Maven Central.  Let me know if you need help.

**Comment by pdavidson100** [comment]
Yes, we're planning to set up a Travis CI pipeline that deploys to Maven Central.

**Comment by jamesward** [comment]
I've been meaning to write up instructions on how I think that should be done.  In the meantime, here is a sample project that has it fully automated on git tag creation:
https://github.com/jamesward/travis-central-test

**Comment by pdavidson100** [comment]
The Mirus artifacts are now available in Maven Central:  http://central.maven.org/maven2/com/salesforce/mirus/mirus/
