### ISSUE TITLE
Enabling SSL connectivity

### ISSUE THREAD

**Issue by Hari4AMQ** [salesforce/mirus#32]
Hi Mirus team,

I'm able to mirror data from source to destination for a topic with open (*) permissions on port 9092. But, I'm not able to setup/mirror data over SSL connection. Can you help with the steps/document (if any) to set SSL connectivity.

Regards,
Hari

**Comment by dalassi1** [comment]
Hi @Hari4AMQ ,

For starter, have a look at the KC documentation referenced in the README: https://github.com/salesforce/mirus#kafka-connect-configuration

There are different SSL settings that you will need to configure. The internal KC Admin clients would be using the standard Java SSL config names such `ssl.keystore.location`, `ssl.keystore.password`, etc. There are also configs related to the Kafka Producer (KC Sink) which would be prefixed with `producer.`. The Kafka Consumers (KC Source) would be prefixed with `consumer.`. For example, you should have in your source config `consumer.ssl.keystore.location` and `consumer.ssl.keystore.password` configurations instead of calling them `ssl.keystore.location` and `ssl.keystore.password`. 

HTH!
Derar

**Comment by Hari4AMQ** [comment]
Hi Derar,

Thanks for your response!

Yes, I've made the SSL changes that you suggest. But, I'm getting the below exception:

**Comment by Hari4AMQ** [comment]
I changed `client.dns.lookup` to `resolve_canonical_bootstrap_servers_only` from default but it did not help. I see from the logs that the process is starting and throwing the above error on servers listed with `consumer.bootstrap.servers` .

**Comment by dalassi1** [comment]
You should be able to add other names/IPs to the SAN (Subject Alternative Names). SAN is actually the proper way to validate host names when establishing SSL connections although CN should still work. So I would create another cert with the IP and hostname in the SAN.

**Comment by dalassi1** [comment]
You can also unset this SSL property `ssl.endpoint.identification.algorithm`. Its default is `https` which will validate the hostname against what the cert has in the CN and SAN. So basically you can relax it which might help if you cannot create another cert.

**Comment by Hari4AMQ** [comment]
I tried unsetting this SSL property `ssl.endpoint.identification.algorithm` and could see that the connector came to running state but the with empty tasks list. 

Below is the configurations that I'm using:
`worker.properties` file:
```
bootstrap.servers=<brokerDNS>:9093
group.id=mirus-test8
key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
header.converter=org.apache.kafka.connect.converters.ByteArrayConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
config.storage.topic=mirus-config
status.storage.topic=mirus-status
offset.storage.topic=mirus-offsets

producer.ssl.endpoint.identification.algorithm=
consumer.ssl.endpoint.identification.algorithm=

ssl.endpoint.identification.algorithm=

# In a production environment these values should be increased
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

security.protocol=SSL
ssl.truststore.location=<path>truststore.jks
ssl.truststore.password=<password>
ssl.keystore.location=<path>keystore.jks
ssl.keystore.password=<password>
ssl.key.password=<password>
```

**Comment by Hari4AMQ** [comment]
I had to correct a typo to fix the above issue. Now, I'm able to see that the task's are getting listed 
```
[
    {
        "id": {
            "connector": "mirus-10",
            "task": 0
        },
        "config": {
            "partitions": "[{\"topic\":\"test-mirus-ssl\",\"partition\":0}]",
            "consumer.ssl.truststore.password": "<password>",
            "consumer.ssl.endpoint.identification.algorithm": "",
            "consumer.ssl.truststore.location": "<path>truststore.jks",
            "destination.topic.name.suffix": "",
            "consumer.bootstrap.servers": "BrokerDNS:9093",
            "task.class": "com.salesforce.mirus.MirusSourceTask",
            "consumer.value.deserializer": "org.apache.kafka.common.serialization.ByteArrayDeserializer",
            "consumer.security.protocol": "SSL",
            "consumer.ssl.keystore.location": "<path>keystore.jks",
            "consumer.ssl.keystore.password": "<password>",
            "consumer.client.id": "mirus-10mirus-10-0",
            "consumer.key.deserializer": "org.apache.kafka.common.serialization.ByteArrayDeserializer"
        }
    },
    {
        "id": {
            "connector": "mirus-10",
            "task": 1
```

However, I'm see timeout at the producer with the below error:

**Comment by pdavidson100** [comment]
@Hari4AMQ Your producer configuration needs to be in `worker.properties`, not in the source connector configuration.  Try moving all your `producer.*` settings into `worker.properties`.  When you're having trouble configuring Kafka Connect is often helps to temporarily change your logging level to DEBUG, this can help isolate your problem.

**Comment by Hari4AMQ** [comment]
Thanks much @pdavidson100 @dalassi1 , I'm able to mirror data using Mirus on 9093 port.
