### ISSUE TITLE
failed to run the quick start example

### ISSUE THREAD

**Issue by windtalker** [salesforce/mirus#36]
I have a try of mirus, but failed to run the quick start example, I always failed in step 4:
 curl localhost:8083
curl: (7) Failed to connect to localhost port 8083: Connection refused

From the source code in Mirus.java, I do not find any code to start the rest server, is there anything I missed?

BTW, I can run the quick start example after adding some code in Mirus.java to start the rest server.

**Comment by dalassi1** [comment]
Can you provide errors or warning in the logs?

**Comment by windtalker** [comment]
Hi, 
I've found the root cause, the kafka version I using is 2.1.1, before KAFKA-7503(https://issues.apache.org/jira/browse/KAFKA-7503), the rest server is started in the start() function in connect.java, but the start logic is moved after KAFKA-7503, so I think in order to run with kafka 2.1.1, mirus should start the rest server in its own start logic.

**Comment by pdavidson100** [comment]
Thanks @windtalker. I've submitted a PR that pulls through this and other changes, as well as updating to 2.2.0. https://github.com/salesforce/mirus/pull/38

**Comment by pdavidson100** [comment]
Fix for this issue has been merged.
