### ISSUE TITLE
Can we manipulate the filter any of the config parameters(eg. password configuration) during the GET call

### ISSUE THREAD

**Issue by Hari4AMQ** [salesforce/mirus#40]
While doing the GET operation for displaying Task status, I'm seeing passwords in plain text. Is there any way to edit/mask the config parameters (like passwords in my case) while doing the GET call

Below is the sample example:

curl localhost:8083/connectors/source-2-destination/tasks | jq

[
  {
    "id": {
      "connector": "source-2-destination",
      "task": 0
    },
    "config": {
      "partitions": "[{\"topic\":\"topicname\",\"partition\":0}]",
      `"consumer.ssl.truststore.password": "<plaintext password>",`
      "consumer.ssl.endpoint.identification.algorithm": "",
      "consumer.group.id": "mirus-source-2-destination-grp",
      "consumer.ssl.truststore.location": "/path/<truststore>.jks",
      "consumer.bootstrap.servers": "destination-kafka-cluster:9093",
      "task.class": "com.salesforce.mirus.MirusSourceTask",
      "consumer.value.deserializer": "org.apache.kafka.common.serialization.ByteArrayDeserializer",
      "consumer.security.protocol": "SSL",
      "consumer.ssl.keystore.location": "/path/keystore.jks",
     ` "consumer.ssl.keystore.password": "<plaintext password>",`
      "consumer.client.id": "source-2-destinationsource-2-destination-0",
      "consumer.key.deserializer": "org.apache.kafka.common.serialization.ByteArrayDeserializer"
    }
  },

**Comment by cricket007** [comment]
You can externalize the secrets by following the changes made by 

https://issues.apache.org/jira/browse/KAFKA-6886

https://cwiki.apache.org/confluence/display/KAFKA/KIP-297%3A+Externalizing+Secrets+for+Connect+Configurations

**Comment by Hari4AMQ** [comment]
Thanks for your reply!
We are able externalize password for a "PUT" call.
But, during the `GET service/connector-name` and `GET service/connector-name/tasks` operations we are seeing password in plain-text instead of showing in 
`${file:<file-location>:<property-name>}`

**Comment by cricket007** [comment]
What version of Connect are you using? There was a JIRA reopened to fix that. I don't know if it is closed yet

**Comment by Hari4AMQ** [comment]
We are using 2.1

**Comment by cricket007** [comment]
See https://issues.apache.org/jira/browse/KAFKA-5117?focusedCommentId=16737143&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16737143
