### ISSUE TITLE
API end point for health check

### ISSUE THREAD

**Issue by chetann** [salesforce/mirus#45]
Is there any endpoint for Mirus, which can be used as service health check?

Basically I have deployed Mirus on K8s and looking for ways to monitor the health of my service.

**Comment by pdavidson100** [comment]
There is currently no built-in dedicated health check endpoint in Mirus or Kafka Connect - users currently need to call the REST API and write their own logic to establish health. This is an issue we're aware of and we may add a dedicated health endpoint to Mirus to make things easier. For now there are some external health check sidecars available for Kafka Connect that would be suitable to use with Mirus, e.g. https://pypi.org/project/kafka-connect-healthcheck/.

**Comment by chetann** [comment]
Thanks.
