### ISSUE TITLE
Mirus deployed in k8s pod is failing with "java.lang.OutOfMemoryError"

### ISSUE THREAD

**Issue by Hari4AMQ** [salesforce/mirus#47]
Our Mirus service running in K8s pod is filing with "java.lang.OutOfMemoryError". Below is the error that we are seeing in our Mirus logs.

```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /tmp/heapdump.bin ...
Heap dump file created [2116271685 bytes in 3.475 secs]

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-2"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-33"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-14"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-13"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "server-timer"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-3"
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at JPLISAgent.c line: 807

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-2"
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at JPLISAgent.c line: 807

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-24"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "kafka-producer-network-thread | producer-23"
```

We tried to increase Max heap size from 2 GB to 5 GB but still issue is not fixed. When checked the heap dumps, we found that the topic message data is occupying most the heap space. We also also tried by configuring the producer with below configs:
```
    producer.buffer.memory=10000000
    producer.batch.size=1000
    producer.acks=1
```

Please suggest on how to over come this issue.

**Comment by pdavidson100** [comment]
Each task contains an independent producer buffer, so you need to allocate enough heap memory to accommodate the all buffers for as many tasks as you plan to assign to each worker instance.  Your options include reducing the max task count, increasing heap allocation, increasing the number of workers in the cluster, and reducing the producer buffer size. For comparison we typically run each worker with a 28G heap and a 50MB producer buffer for each task, but we run in an unusual "push" configuration where Mirus is colocated with the source cluster.  Our buffer (and heap) is much larger than would be necessary if Mirus was co-located with the destination cluster and could send data over a low-latency network (which is recommended).

**Comment by Hari4AMQ** [comment]
Thanks @pdavidson100
