### ISSUE TITLE
Can Mirus run as a Kafka Connect connector?

### ISSUE THREAD

**Issue by javierholguera** [salesforce/mirus#54]
We already have a Kafka Connect cluster, so it would be ideal to run Mirus as yet another connector in our cluster instead of running it as a separate server. Is this possible?

Thanks.

**Comment by pdavidson100** [comment]
That should be possible, Mirus would simply run without our additional metrics and failed task auto-restart functionality.

**Comment by javierholguera** [comment]
👍
