### ISSUE TITLE
ReplayPolicy.IGNORE does not process new records

### ISSUE THREAD

**Issue by savinov** [salesforce/mirus#87]
ReplayPolicy.IGNORE filters all the messages: duplicates and a new ones.
The policy is set by default, so mirus just ignores all the messages from the source cluster, which is useless.
See:
https://github.com/salesforce/mirus/issues/65
https://github.com/salesforce/mirus/pull/64#discussion_r782907492
https://github.com/salesforce/mirus/blob/master/src/main/java/com/salesforce/mirus/MirusSourceTask.java#L256

**Comment by pdavidson100** [comment]
Thanks for reporting @savinov .  PR for a fix submitted here https://github.com/salesforce/mirus/pull/88

**Comment by pdavidson100** [comment]
Fix merged. Closing issue.
